import React, { useMemo, useState } from 'react';
import { Activity, Calendar } from '../common/Icons';
import { useApp } from '../../context/AppContext';
import { dayTotals, formatFocusTime, localDateKey } from '../../utils/focusData';

const Metric = ({ title, value }) => <div className="glass-panel rounded-2xl border border-neutral-800 p-4"><p className="text-[11px] font-bold uppercase tracking-wider text-neutral-400">{title}</p><p className="mt-2 text-xl font-bold text-white">{value}</p></div>;

export const AnalyticsView = () => {
  const { focusSessions, reminders, streak, dailyGoalMinutes, checklists, moodEntries, moodOptions, selectedDate, setSelectedDate } = useApp();
  const [range, setRange] = useState(7);
  const totals = useMemo(() => dayTotals(focusSessions), [focusSessions]);
  const selectedSessions = focusSessions.filter((session) => session.date === selectedDate);
  const selectedMinutes = selectedSessions.reduce((total, session) => total + session.minutes, 0);
  const selectedTasks = checklists.flatMap((list) => list.tasks).filter((task) => task.date === selectedDate);
  const selectedTaskDone = selectedTasks.filter((task) => task.completed).length;
  const selectedReminders = reminders.filter((reminder) => reminder.date === selectedDate);
  const selectedReminderDone = selectedReminders.filter((reminder) => reminder.completed).length;
  const selectedMood = moodEntries.find((entry) => entry.date === selectedDate);
  const selectedMoodOption = moodOptions.find((option) => option.id === selectedMood?.mood);
  const selectedGoalPercent = Math.min(100, Math.round((selectedMinutes / dailyGoalMinutes) * 100));
  const dateLabel = new Date(`${selectedDate}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
  const anchor = new Date(`${selectedDate}T12:00:00`);
  const weekDates = Array.from({ length: 7 }, (_, index) => { const date = new Date(anchor); date.setDate(anchor.getDate() - (6 - index)); return localDateKey(date); });
  const weekMinutes = weekDates.reduce((sum, date) => sum + (totals[date] || 0), 0);
  const weekSessions = focusSessions.filter((session) => weekDates.includes(session.date)).length;
  const max = Math.max(...weekDates.map((date) => totals[date] || 0), 1);
  const rangeDates = Array.from({ length: range }, (_, index) => { const date = new Date(anchor); date.setDate(date.getDate() - (range - 1 - index)); return localDateKey(date); });
  const rangeMax = Math.max(...rangeDates.map((date) => totals[date] || 0), 1);
  const longest = focusSessions.length ? Math.max(...focusSessions.map((session) => session.minutes)) : 0;
  const bestDate = Object.entries(totals).sort((first, second) => second[1] - first[1])[0];
  const mostProductive = bestDate;

  return <div className="space-y-7 animate-fadeIn"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Insights</p><h1 className="mt-1 text-3xl font-bold text-white">Focus analytics</h1><p className="mt-1 text-sm text-neutral-400">Viewing your focus, tasks, reminders, and mood for one chosen day.</p></div><label className="flex items-center gap-2 rounded-xl border border-emerald-400/15 bg-emerald-400/[.04] px-3 py-2 text-xs font-semibold text-neutral-300"><Calendar className="h-4 w-4 text-emerald-400" /><input type="date" value={selectedDate} onChange={(event) => setSelectedDate(event.target.value)} className="bg-transparent outline-none" aria-label="Selected workspace date" /></label></div>
  <section><div className="mb-3 flex items-baseline justify-between gap-4"><h2 className="text-sm font-bold text-white">{dateLabel}</h2><span className="text-xs text-neutral-500">Selected in Calendar</span></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-6"><Metric title="Focus" value={formatFocusTime(selectedMinutes)} /><Metric title="Sessions" value={selectedSessions.length} /><Metric title="Checklist" value={`${selectedTaskDone} / ${selectedTasks.length}`} /><Metric title="Reminders" value={`${selectedReminderDone} / ${selectedReminders.length}`} /><Metric title="Mood" value={selectedMoodOption ? `${selectedMoodOption.emoji} ${selectedMoodOption.label}` : '—'} /><Metric title="Goal" value={`${selectedGoalPercent}%`} /></div><div className="mt-4 rounded-2xl border border-neutral-800 bg-black/10 p-4"><div className="flex justify-between text-xs"><span className="text-neutral-300">Daily goal</span><span className="font-bold text-emerald-400">{formatFocusTime(selectedMinutes)} / {formatFocusTime(dailyGoalMinutes)}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-neutral-800"><div className="h-full bg-emerald-500" style={{ width: `${selectedGoalPercent}%` }} /></div></div></section>
  <section className="glass-panel rounded-3xl border border-neutral-800 p-6"><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-emerald-400" /><div><h2 className="font-bold text-white">Week ending {new Date(`${selectedDate}T12:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</h2><p className="text-xs text-neutral-400">{formatFocusTime(weekMinutes)} across {weekSessions} sessions</p></div></div><div className="mt-8 flex h-44 items-end gap-3">{weekDates.map((date) => <div className="flex h-full flex-1 flex-col items-center justify-end gap-2" key={date}><span className="text-[10px] text-neutral-300">{totals[date] || 0}m</span><div className={`min-h-1 w-full max-w-12 rounded-t-lg ${date === selectedDate ? 'bg-emerald-300' : 'bg-emerald-500/80'}`} style={{ height: `${((totals[date] || 0) / max) * 100}%` }} /><span className="text-[10px] text-neutral-500">{new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: 'short' })}</span></div>)}</div></section>
  <section className="glass-panel rounded-3xl border border-neutral-800 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-white">Focus trends</h2><p className="text-xs text-neutral-400">Focus minutes ending on the selected date</p></div><div className="flex gap-1">{[7, 30, 90].map((days) => <button type="button" key={days} onClick={() => setRange(days)} className={`rounded-lg px-2.5 py-1 text-xs ${range === days ? 'bg-emerald-500 text-white' : 'text-neutral-400 hover:bg-neutral-800'}`}>{days === 90 ? '3 Months' : `${days} Days`}</button>)}</div></div><div className="mt-7 flex h-44 items-end gap-1 overflow-hidden">{rangeDates.map((date) => <div className="flex h-full min-w-1 flex-1 items-end" key={date} title={`${date}: ${totals[date] || 0} minutes`}><div className={`min-h-1 w-full rounded-t-sm ${date === selectedDate ? 'bg-emerald-300' : 'bg-emerald-500/80'}`} style={{ height: `${((totals[date] || 0) / rangeMax) * 100}%` }} /></div>)}</div></section>
  <section className="grid gap-6 lg:grid-cols-2"><div className="glass-panel rounded-3xl border border-neutral-800 p-6"><h2 className="font-bold text-white">Selected-day sessions</h2><div className="mt-4 space-y-2">{selectedSessions.map((session) => <div className="flex justify-between gap-4 border-b border-neutral-800 pb-2 text-sm" key={session.id}><span className="text-white">{new Date(session.completedAt).toLocaleString(undefined, { hour: 'numeric', minute: '2-digit' })}</span><span className="font-bold text-emerald-300">{formatFocusTime(session.minutes)}</span></div>)}{!selectedSessions.length && <p className="text-sm text-neutral-500">No completed focus sessions for this date.</p>}</div></div><div className="glass-panel rounded-3xl border border-neutral-800 p-6"><h2 className="font-bold text-white">All time</h2><div className="mt-4 grid grid-cols-2 gap-3"><Metric title="Total focus" value={formatFocusTime(focusSessions.reduce((sum, session) => sum + session.minutes, 0))} /><Metric title="Total sessions" value={focusSessions.length} /><Metric title="Longest" value={formatFocusTime(longest)} /><Metric title="Current streak" value={`${streak.current} days`} /></div>{mostProductive && <p className="mt-4 text-sm text-neutral-400">Best focus day: <span className="font-bold text-white">{new Date(`${mostProductive[0]}T12:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</span> with {formatFocusTime(mostProductive[1])}.</p>}</div></section></div>;
};
