import React, { useState } from 'react';
import { Activity } from '../common/Icons';
import { useApp } from '../../context/AppContext';
import { dayTotals, formatFocusTime, localDateKey } from '../../utils/focusData';

const Metric = ({ title, value }) => <div className="glass-panel rounded-2xl p-4 border border-neutral-800"><p className="text-[11px] text-neutral-400 uppercase tracking-wider font-bold">{title}</p><p className="text-xl mt-2 font-bold text-white">{value}</p></div>;
export const AnalyticsView = () => {
  const { focusSessions, reminders, streak, dailyGoalMinutes, checklists } = useApp(); const [range, setRange] = useState(7); const totals = dayTotals(focusSessions); const today = localDateKey();
  const todaySessions = focusSessions.filter((s) => s.date === today); const anchor = new Date(`${today}T12:00:00`); const weekDates = Array.from({ length: 7 }, (_, i) => { const date = new Date(anchor); date.setDate(anchor.getDate() - (6 - i)); return localDateKey(date); });
  const weekMinutes = weekDates.reduce((sum, date) => sum + (totals[date] || 0), 0); const max = Math.max(...weekDates.map((d) => totals[d] || 0), 1);
  const longest = focusSessions.length ? Math.max(...focusSessions.map((s) => s.minutes)) : 0;
  const bestDate = Object.entries(totals).sort((a, b) => b[1] - a[1])[0];
  const quality = focusSessions.filter(s => s.quality).map(s => s.quality); const planned = reminders.length; const finished = reminders.filter(r => r.completed).length; const mostProductive = Object.entries(totals).sort((a,b)=>b[1]-a[1])[0];
  const todayMinutes = todaySessions.reduce((a, s) => a + s.minutes, 0); const taskTotal = checklists.reduce((sum, list) => sum + list.tasks.length, 0); const taskDone = checklists.reduce((sum, list) => sum + list.tasks.filter(t => t.completed).length, 0); const goalPercent = Math.min(100, Math.round(todayMinutes / dailyGoalMinutes * 100));
  const rangeDates = Array.from({ length: range }, (_, index) => { const date = new Date(`${today}T12:00:00`); date.setDate(date.getDate() - (range - 1 - index)); return localDateKey(date); }); const rangeMax = Math.max(...rangeDates.map(date => totals[date] || 0), 1);
  return <div className="space-y-7 animate-fadeIn"><div><p className="text-emerald-400 text-xs font-bold uppercase tracking-[.2em]">Insights</p><h1 className="text-3xl font-bold text-white mt-1">Focus analytics</h1><p className="text-sm text-neutral-400 mt-1">A clear record of how you actually spend your focus time.</p></div>
  <section><h2 className="text-sm font-bold text-white mb-3">Overview</h2><div className="grid grid-cols-2 lg:grid-cols-6 gap-4"><Metric title="Today's focus" value={formatFocusTime(todayMinutes)}/><Metric title="Today sessions" value={todaySessions.length}/><Metric title="Current streak" value={`${streak.current} days`}/><Metric title="Tasks completed" value={`${taskDone} / ${taskTotal}`}/><Metric title="Average session" value={formatFocusTime(todaySessions.length ? todayMinutes/todaySessions.length : 0)}/><Metric title="Goal" value={`${goalPercent}%`}/></div><div className="mt-4 glass-panel rounded-2xl p-4 border border-neutral-800"><div className="flex justify-between text-xs"><span className="text-neutral-300">Today’s goal</span><span className="text-emerald-400 font-bold">{formatFocusTime(todayMinutes)} / {formatFocusTime(dailyGoalMinutes)}</span></div><div className="h-1.5 rounded-full bg-neutral-800 mt-2 overflow-hidden"><div className="h-full bg-emerald-500" style={{width:`${goalPercent}%`}}/></div></div></section>
  <section className="glass-panel rounded-3xl p-6 border border-neutral-800"><div className="flex items-center gap-2"><Activity className="w-5 h-5 text-emerald-400"/><div><h2 className="font-bold text-white">This week</h2><p className="text-xs text-neutral-400">{formatFocusTime(weekMinutes)} across {focusSessions.filter(s => weekDates.includes(s.date)).length} sessions</p></div></div><div className="mt-8 h-44 flex items-end gap-3">{weekDates.map((date) => <div className="flex-1 flex flex-col items-center gap-2 h-full justify-end" key={date}><span className="text-[10px] text-neutral-300">{totals[date] || 0}m</span><div className="w-full max-w-12 rounded-t-lg bg-emerald-500/80 min-h-1" style={{height: `${((totals[date] || 0) / max) * 100}%`}}/><span className="text-[10px] text-neutral-500">{new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{weekday:'short'})}</span></div>)}</div></section>
  <section className="glass-panel rounded-3xl p-6 border border-neutral-800"><div className="flex flex-wrap justify-between gap-3 items-center"><div><h2 className="font-bold text-white">Focus trends</h2><p className="text-xs text-neutral-400">Focus minutes by day</p></div><div className="flex gap-1">{[7,30,90].map(days => <button key={days} onClick={()=>setRange(days)} className={`px-2.5 py-1 rounded-lg text-xs ${range===days?'bg-emerald-500 text-white':'text-neutral-400 hover:bg-neutral-800'}`}>{days===90?'3 Months':`${days} Days`}</button>)}</div></div><div className="mt-7 h-44 flex items-end gap-1 overflow-hidden">{rangeDates.map((date) => <div className="flex-1 min-w-1 h-full flex items-end" key={date} title={`${date}: ${totals[date] || 0} minutes`}><div className="w-full bg-emerald-500/80 rounded-t-sm min-h-1" style={{height:`${((totals[date]||0)/rangeMax)*100}%`}}/></div>)}</div></section>
  <section><h2 className="text-sm font-bold text-white mb-3">All time</h2><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Metric title="Total focus" value={formatFocusTime(focusSessions.reduce((a,s)=>a+s.minutes,0))}/><Metric title="Total sessions" value={focusSessions.length}/><Metric title="Longest session" value={formatFocusTime(longest)}/><Metric title="Best focus day" value={bestDate ? `${formatFocusTime(bestDate[1])}` : '—'}/></div></section>
  <section className="glass-panel rounded-3xl p-6 border border-neutral-800"><h2 className="font-bold text-white">Productivity insights</h2><div className="mt-4 space-y-2 text-sm text-neutral-300">{focusSessions.length >= 3 && <p>Your average focus session is <span className="text-white font-bold">{formatFocusTime(focusSessions.reduce((a,s)=>a+s.minutes,0)/focusSessions.length)}</span>.</p>}{mostProductive && <p>Your most productive day was <span className="text-white font-bold">{new Date(`${mostProductive[0]}T12:00:00`).toLocaleDateString(undefined,{weekday:'long'})}</span>.</p>}{planned >= 3 && <p>You completed <span className="text-white font-bold">{Math.round(finished/planned*100)}%</span> of planned tasks.</p>}{quality.length >= 3 && <p>Average focus quality: <span className="text-white font-bold">{(quality.reduce((a,b)=>a+b,0)/quality.length).toFixed(1)} / 5</span>.</p>}</div></section><section className="glass-panel rounded-3xl p-6 border border-neutral-800"><h2 className="font-bold text-white">Recent focus history</h2><div className="mt-4 space-y-2">{focusSessions.slice(-8).reverse().map(s => <div className="flex justify-between gap-4 text-sm border-b border-neutral-800 pb-2" key={s.id}><div><span className="text-white">{new Date(s.completedAt).toLocaleString(undefined,{hour:'numeric',minute:'2-digit'})} — {s.minutes} min</span>{s.note && <p className="text-xs text-neutral-400 mt-1">{s.note}</p>}</div>{s.quality && <span className="text-amber-400">{'★'.repeat(s.quality)}</span>}</div>)}{!focusSessions.length && <p className="text-sm text-neutral-500">Completed sessions will appear here.</p>}</div></section></div>;
};
