import React, { useState } from 'react';
import { CheckSquare, Plus, Trash2, CheckCircle2, Circle } from '../common/Icons';
import { useApp } from '../../context/AppContext';

export const ChecklistsView = () => {
  const { checklists, addChecklist, deleteChecklist, addChecklistTask, updateChecklistTask, deleteChecklistTask } = useApp();
  const [activeId, setActiveId] = useState(checklists[0]?.id); const [task, setTask] = useState(''); const [listName, setListName] = useState('');
  const active = checklists.find((list) => list.id === activeId) || checklists[0];
  const submitTask = (event) => { event.preventDefault(); addChecklistTask(active.id, task); setTask(''); };
  const submitList = (event) => { event.preventDefault(); if (!listName.trim()) return; addChecklist(listName); setListName(''); };
  const done = active?.tasks.filter((item) => item.completed).length || 0; const total = active?.tasks.length || 0;
  return <div className="grid lg:grid-cols-[230px_1fr] gap-6 animate-fadeIn"><aside className="glass-panel rounded-3xl p-4 border border-neutral-800 h-fit"><p className="px-2 text-[11px] font-bold uppercase tracking-wider text-neutral-400">Checklists</p><div className="mt-3 space-y-1">{checklists.map((list) => <button onClick={() => setActiveId(list.id)} key={list.id} className={`w-full text-left px-3 py-2.5 rounded-xl text-sm ${active?.id === list.id ? 'bg-emerald-500 text-white' : 'text-neutral-300 hover:bg-neutral-800'}`}>{list.name}</button>)}</div><form onSubmit={submitList} className="mt-4 flex gap-2"><input value={listName} onChange={(e) => setListName(e.target.value)} placeholder="New list" className="glass-input min-w-0 flex-1 px-2 py-2 rounded-lg text-xs"/><button className="btn-emerald p-2 rounded-lg"><Plus className="w-4 h-4"/></button></form></aside>
  {active && <section className="glass-panel rounded-3xl p-6 sm:p-8 border border-neutral-800"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><CheckSquare className="w-5 h-5 text-emerald-400"/><h1 className="text-2xl font-bold text-white">{active.name}</h1></div><p className="text-sm text-neutral-400 mt-2">{done} / {total} completed</p></div><button onClick={() => { deleteChecklist(active.id); setActiveId(checklists.find(l => l.id !== active.id)?.id); }} className="text-neutral-500 hover:text-red-400 p-2" aria-label="Delete checklist"><Trash2 className="w-4 h-4"/></button></div><div className="mt-4 h-2 rounded-full bg-neutral-800 overflow-hidden"><div className="h-full bg-emerald-500 rounded-full transition-all" style={{width: `${total ? done / total * 100 : 0}%`}}/></div><form onSubmit={submitTask} className="flex gap-2 mt-7"><input value={task} onChange={(e)=>setTask(e.target.value)} className="glass-input flex-1 px-4 py-3 rounded-xl text-sm" placeholder="Add a task and press Enter"/><button className="btn-emerald px-4 rounded-xl text-sm font-bold">Add</button></form><div className="mt-5 space-y-2">{active.tasks.length ? active.tasks.map((item) => <div key={item.id} className="flex items-center gap-3 p-3 rounded-xl bg-neutral-900/70 border border-neutral-800"><button onClick={() => updateChecklistTask(active.id, item.id, { completed: !item.completed })}>{item.completed ? <CheckCircle2 className="w-5 h-5 text-emerald-400"/> : <Circle className="w-5 h-5 text-neutral-500"/>}</button><input value={item.title} onChange={(e)=>updateChecklistTask(active.id,item.id,{title:e.target.value})} className={`bg-transparent outline-none flex-1 text-sm ${item.completed ? 'line-through text-neutral-500' : 'text-white'}`}/><button onClick={() => deleteChecklistTask(active.id,item.id)} className="text-neutral-500 hover:text-red-400"><Trash2 className="w-4 h-4"/></button></div>) : <p className="text-sm text-neutral-500 py-8 text-center">Add the first task for this list.</p>}</div></section>}</div>;
};
