import React, { useMemo, useState } from 'react';
import { Calendar, CheckCircle2, Heart, Sparkles } from '../common/Icons';
import { useApp } from '../../context/AppContext';
import { dayTotals, formatFocusTime, localDateKey } from '../../utils/focusData';

const dateBefore = (dateString, offset) => {
  const date = new Date(`${dateString}T12:00:00`);
  date.setDate(date.getDate() - offset);
  return localDateKey(date);
};

const MoodCheckInForm = ({ entry, moodOptions, recordMood, selectedDate }) => {
  const [selectedMood, setSelectedMood] = useState(entry?.mood || 'good');
  const [note, setNote] = useState(entry?.note || '');
  const [hasSaved, setHasSaved] = useState(Boolean(entry));

  const submitCheckIn = (event) => {
    event.preventDefault();
    recordMood(selectedMood, note, selectedDate);
    setHasSaved(true);
  };

  return <form onSubmit={submitCheckIn} className="mt-6"><div className="grid grid-cols-1 gap-2 sm:grid-cols-5">{moodOptions.map((option) => { const active = selectedMood === option.id; return <button key={option.id} type="button" onClick={() => setSelectedMood(option.id)} aria-pressed={active} className={`rounded-2xl border p-3 text-left transition-all focus:outline-none focus:ring-2 focus:ring-emerald-400/50 ${active ? 'border-emerald-400/60 bg-emerald-400/10 shadow-lg shadow-emerald-500/10' : 'border-neutral-800 bg-black/10 hover:border-neutral-600 hover:bg-white/[.035]'}`}><span className="block text-2xl">{option.emoji}</span><span className="mt-2 block text-sm font-bold text-white">{option.label}</span><span className="mt-0.5 block text-[11px] leading-4 text-neutral-400">{option.description}</span></button>; })}</div><label className="mt-5 block text-sm font-semibold text-neutral-200" htmlFor={`mood-note-${selectedDate}`}>A small note <span className="font-normal text-neutral-500">(optional)</span></label><textarea id={`mood-note-${selectedDate}`} value={note} maxLength={240} onChange={(event) => setNote(event.target.value)} placeholder="What’s influencing how you feel?" className="glass-input mt-2 h-28 w-full resize-none rounded-2xl p-3 text-sm" /><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-neutral-500">{note.length}/240 characters</p><button type="submit" className="btn-emerald inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold"><CheckCircle2 className="h-4 w-4" />{hasSaved ? 'Update check-in' : 'Save check-in'}</button></div></form>;
};

export const MoodView = () => {
  const { moodEntries, moodOptions, recordMood, focusSessions, selectedDate, setSelectedDate } = useApp();
  const moodsByDate = useMemo(() => new Map(moodEntries.map((entry) => [entry.date, entry])), [moodEntries]);
  const selectedEntry = moodsByDate.get(selectedDate);
  const selectedOption = moodOptions.find((option) => option.id === selectedEntry?.mood);
  const selectedDateLabel = new Date(`${selectedDate}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
  const week = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = dateBefore(selectedDate, 6 - index); return { date, entry: moodsByDate.get(date) }; }), [moodsByDate, selectedDate]);
  const weeklyEntries = week.map(({ entry }) => entry).filter(Boolean);
  const weeklyAverage = weeklyEntries.length ? (weeklyEntries.reduce((sum, entry) => sum + (moodOptions.find((option) => option.id === entry.mood)?.score || 0), 0) / weeklyEntries.length).toFixed(1) : null;
  const recentEntries = [...moodEntries].slice(-5).reverse();
  const focusByDay = useMemo(() => dayTotals(focusSessions), [focusSessions]);
  const moodFocusPatterns = useMemo(() => moodOptions.map((option) => { const entries = moodEntries.filter((entry) => entry.mood === option.id); const focusMinutes = entries.reduce((total, entry) => total + (focusByDay[entry.date] || 0), 0); return { ...option, checkIns: entries.length, averageFocusMinutes: entries.length ? focusMinutes / entries.length : 0 }; }).filter((pattern) => pattern.checkIns > 0), [focusByDay, moodEntries, moodOptions]);
  const clearestPattern = [...moodFocusPatterns].filter((pattern) => pattern.checkIns >= 2).sort((first, second) => second.averageFocusMinutes - first.averageFocusMinutes)[0];

  return <div className="space-y-7 animate-fadeIn"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Daily reflection</p><h1 className="mt-1 text-3xl font-bold text-white">Mood tracker</h1><p className="mt-1 text-sm text-neutral-400">A private place to notice how you’re doing, one day at a time.</p></div><label className="flex items-center gap-2 rounded-xl border border-emerald-400/15 bg-emerald-400/[.04] px-3 py-2 text-xs font-semibold text-neutral-300"><Calendar className="h-4 w-4 text-emerald-400" /><input type="date" value={selectedDate} onChange={(event) => setSelectedDate(event.target.value)} className="bg-transparent outline-none" aria-label="Selected workspace date" /></label></div>
  <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="glass-panel rounded-3xl border border-neutral-800 p-5 shadow-xl sm:p-6"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl border border-emerald-400/25 bg-emerald-400/10"><Heart className="h-5 w-5 text-emerald-300" /></div><div><h2 className="font-bold text-white">How did you feel on {selectedDateLabel}?</h2><p className="mt-1 text-xs text-neutral-400">This check-in is synced with the date selected in Calendar.</p></div></div><MoodCheckInForm key={selectedDate} entry={selectedEntry} moodOptions={moodOptions} recordMood={recordMood} selectedDate={selectedDate} /></section>
  <section className="glass-panel rounded-3xl border border-neutral-800 p-5 sm:p-6"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-emerald-400" /><h2 className="font-bold text-white">Week ending this day</h2></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-neutral-800 bg-black/15 p-4"><p className="text-xs text-neutral-400">Check-ins</p><p className="mt-1 text-2xl font-bold text-white">{weeklyEntries.length}<span className="text-sm text-neutral-500"> / 7</span></p></div><div className="rounded-2xl border border-neutral-800 bg-black/15 p-4"><p className="text-xs text-neutral-400">Average mood</p><p className="mt-1 text-2xl font-bold text-white">{weeklyAverage || '—'}<span className="text-sm text-neutral-500">{weeklyAverage ? ' / 5' : ''}</span></p></div></div><div className="mt-5 grid grid-cols-7 gap-1.5">{week.map(({ date, entry }) => { const option = entry && moodOptions.find((mood) => mood.id === entry.mood); return <button type="button" key={date} onClick={() => setSelectedDate(date)} title={option ? `${date}: ${option.label}` : `${date}: no check-in`} className={`text-center ${date === selectedDate ? 'rounded-xl ring-1 ring-emerald-400/70' : ''}`}><span className={`flex aspect-square items-center justify-center rounded-xl border text-lg ${option ? 'border-emerald-400/25 bg-emerald-400/[.08]' : 'border-neutral-800 bg-black/10 text-neutral-600'}`}>{option?.emoji || '·'}</span><span className="mt-1 block text-[10px] text-neutral-500">{new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: 'narrow' })}</span></button>; })}</div>{selectedOption && <p className="mt-5 rounded-xl border border-emerald-400/15 bg-emerald-400/[.045] p-3 text-xs leading-5 text-neutral-300">On this day, you chose <span className="font-bold text-white">{selectedOption.emoji} {selectedOption.label}</span>. {selectedOption.description}.</p>}</section></div>
  <section className="glass-panel rounded-3xl border border-neutral-800 p-5 sm:p-6"><div className="flex items-center gap-2"><Calendar className="h-5 w-5 text-emerald-400" /><div><h2 className="font-bold text-white">Recent check-ins</h2><p className="mt-0.5 text-xs text-neutral-400">Select a check-in to view that day everywhere in the workspace.</p></div></div><div className="mt-5 space-y-3">{recentEntries.map((entry) => { const option = moodOptions.find((mood) => mood.id === entry.mood); return <button type="button" onClick={() => setSelectedDate(entry.date)} key={entry.date} className={`flex w-full gap-3 rounded-2xl border p-4 text-left transition-colors ${entry.date === selectedDate ? 'border-emerald-400/50 bg-emerald-400/[.06]' : 'border-neutral-800 bg-black/10 hover:border-neutral-700'}`}><span className="text-2xl" aria-hidden="true">{option?.emoji}</span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-baseline justify-between gap-x-3"><span className="text-sm font-bold text-white">{option?.label}</span><time className="text-xs text-neutral-500" dateTime={entry.date}>{new Date(`${entry.date}T12:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</time></span>{entry.note && <span className="mt-1 block whitespace-pre-wrap break-words text-sm leading-6 text-neutral-300">{entry.note}</span>}</span></button>; })}{!recentEntries.length && <div className="rounded-2xl border border-dashed border-neutral-700 p-8 text-center text-sm text-neutral-500">Your check-ins will appear here after you save your first one.</div>}</div></section>
  <section className="glass-panel rounded-3xl border border-neutral-800 p-5 sm:p-6"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl border border-emerald-400/25 bg-emerald-400/[.07]"><Sparkles className="h-5 w-5 text-emerald-400" /></div><div><h2 className="font-bold text-white">Focus & mood</h2><p className="mt-1 text-xs text-neutral-400">A gentle reflection on your logged focus time — not a measure of your worth or productivity.</p></div></div>{moodFocusPatterns.length ? <><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{moodFocusPatterns.map((pattern) => <div key={pattern.id} className="rounded-2xl border border-neutral-800 bg-black/10 p-4"><div className="flex items-center gap-2"><span className="text-xl">{pattern.emoji}</span><span className="text-sm font-bold text-white">{pattern.label}</span></div><p className="mt-3 text-xl font-bold text-white">{formatFocusTime(pattern.averageFocusMinutes)}</p><p className="mt-1 text-xs text-neutral-500">average focus · {pattern.checkIns} {pattern.checkIns === 1 ? 'check-in' : 'check-ins'}</p></div>)}</div>{clearestPattern && <p className="mt-4 rounded-xl border border-emerald-400/15 bg-emerald-400/[.045] p-3 text-sm leading-6 text-neutral-300">Across <span className="font-bold text-white">{clearestPattern.checkIns} {clearestPattern.label.toLowerCase()} check-ins</span>, you logged an average of <span className="font-bold text-white">{formatFocusTime(clearestPattern.averageFocusMinutes)}</span> of focus. Patterns become more useful as you keep checking in.</p>}</> : <div className="mt-5 rounded-2xl border border-dashed border-neutral-700 p-7 text-center text-sm text-neutral-500">Check in on a few days to see your focus time in context.</div>}</section></div>;
};
