import React from 'react';
import { Activity, Flame, CheckCircle2, Circle } from '../common/Icons';
import { useApp } from '../../context/AppContext';
import { dayTotals, formatFocusTime, localDateKey } from '../../utils/focusData';

const Stat = ({ label, value, detail }) => <div className="glass-panel rounded-2xl p-4 border border-neutral-800"><p className="text-[11px] uppercase tracking-wider text-neutral-400 font-bold">{label}</p><p className="text-2xl font-bold text-white mt-2">{value}</p>{detail && <p className="text-xs text-neutral-400 mt-1">{detail}</p>}</div>;

export const ProgressView = () => {
  const { focusSessions, streak, achievements, achievementDefinitions, dailyGoalMinutes, setDailyGoalMinutes } = useApp();
  const totals = dayTotals(focusSessions);
  const todayMinutes = totals[localDateKey()] || 0; const goalPercent = Math.min(100, Math.round(todayMinutes / dailyGoalMinutes * 100)); const remaining = Math.max(0, dailyGoalMinutes - todayMinutes);
  const today = localDateKey();
  const anchor = new Date(`${today}T12:00:00`);
  const dates = Array.from({ length: 28 }, (_, index) => {
    const date = new Date(anchor); date.setDate(anchor.getDate() - (27 - index)); return localDateKey(date);
  });
  const max = Math.max(...Object.values(totals), 1);
  return <div className="space-y-7 animate-fadeIn">
    <div><p className="text-emerald-400 text-xs font-bold uppercase tracking-[.2em]">Consistency</p><h1 className="text-3xl font-bold text-white mt-1">Focus progress</h1><p className="text-neutral-400 text-sm mt-1">Your streak is built only from completed focus sessions.</p></div>
    <section className="glass-panel rounded-3xl p-6 border border-emerald-500/30"><div className="flex flex-col sm:flex-row justify-between gap-4"><div><p className="text-xs uppercase tracking-wider font-bold text-emerald-400">Today's focus</p><p className="text-3xl font-bold text-white mt-2">{formatFocusTime(todayMinutes)} <span className="text-neutral-500 text-xl">/ {formatFocusTime(dailyGoalMinutes)}</span></p><p className="text-xs text-neutral-400 mt-2">{goalPercent >= 100 ? 'Goal completed — wonderful work today.' : `${formatFocusTime(remaining)} remaining · ${goalPercent}% complete`}</p></div><select value={dailyGoalMinutes} onChange={(e) => setDailyGoalMinutes(Number(e.target.value))} className="glass-input h-fit px-3 py-2 rounded-xl text-xs"><option value="30">30 minutes</option><option value="60">1 hour</option><option value="120">2 hours</option><option value="180">3 hours</option><option value="240">4 hours</option><option value="300">5 hours</option></select></div><div className="h-2 rounded-full bg-neutral-800 overflow-hidden mt-5"><div className="h-full bg-emerald-500 rounded-full transition-all" style={{width:`${goalPercent}%`}}/></div></section>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Stat label="Current streak" value={`${streak.current} days`} detail="Complete one focus session daily"/><Stat label="Best streak" value={`${streak.best} days`}/><Stat label="Focused days" value={streak.days.length}/><Stat label="Total focus" value={formatFocusTime(focusSessions.reduce((a, s) => a + s.minutes, 0))}/></div>
    <div className="grid lg:grid-cols-5 gap-6"><section className="glass-panel lg:col-span-3 rounded-3xl p-6 border border-neutral-800"><div className="flex gap-2 items-center"><Flame className="w-5 h-5 text-amber-400"/><h2 className="font-bold text-white">Last 28 days</h2></div><div className="mt-7 grid grid-cols-7 sm:grid-cols-14 gap-2">{dates.map((date) => <div key={date} title={`${date}: ${totals[date] || 0} minutes`} className="aspect-square rounded-lg border border-neutral-800 flex items-center justify-center" style={{ backgroundColor: totals[date] ? `rgba(16,185,129,${0.18 + (totals[date] / max) * 0.72})` : 'rgba(24,24,27,.6)' }}><span className="text-[9px] text-neutral-300">{date.slice(-2)}</span></div>)}</div><p className="text-xs text-neutral-400 mt-5">A filled day means you completed a focus session.</p></section>
    <section className="glass-panel lg:col-span-2 rounded-3xl p-6 border border-neutral-800"><div className="flex gap-2 items-center"><Activity className="w-5 h-5 text-emerald-400"/><h2 className="font-bold text-white">Achievements</h2></div><div className="space-y-3 mt-5 max-h-64 overflow-auto">{achievementDefinitions.map((achievement) => { const unlocked = achievements[achievement.id]; return <div className="flex items-center gap-3 text-sm" key={achievement.id}>{unlocked ? <CheckCircle2 className="w-4 h-4 text-emerald-400"/> : <Circle className="w-4 h-4 text-neutral-600"/>}<div><span className={unlocked ? 'text-white' : 'text-neutral-500'}>{achievement.label}</span>{unlocked && <p className="text-[10px] text-neutral-500">Unlocked {new Date(unlocked).toLocaleDateString()}</p>}</div></div>})}</div></section></div>
  <section className="glass-panel rounded-3xl p-6 border border-neutral-800"><div className="flex justify-between gap-4 items-center"><div><p className="text-xs uppercase tracking-wider font-bold text-emerald-400">Focus garden</p><h2 className="font-bold text-white mt-1">A quiet record of your care</h2><p className="text-xs text-neutral-400 mt-1">Every plant is earned through completed focus time.</p></div><div className="text-4xl" aria-label="Focus garden">{focusSessions.length ? '🌱' : '·'} {focusSessions.reduce((a,s)=>a+s.minutes,0) >= 60 ? '🌿' : ''} {focusSessions.reduce((a,s)=>a+s.minutes,0) >= 300 ? '🪴' : ''} {focusSessions.reduce((a,s)=>a+s.minutes,0) >= 600 ? '🌳' : ''}</div></div></section></div>;
};
