import React, { useState } from 'react';
import { Activity, CheckSquare } from '../common/Icons';
import { useApp } from '../../context/AppContext';
import { dayTotals, formatFocusTime, localDateKey } from '../../utils/focusData';

const weekKey = () => { const date = new Date(`${localDateKey()}T12:00:00`); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return localDateKey(date); };
export const WeeklyReviewView = () => {
  const { focusSessions, reminders, streak, weeklyReflections, setWeeklyReflections } = useApp(); const [key] = useState(weekKey); const [draft, setDraft] = useState(() => weeklyReflections[key] || { wentWell: '', improve: '' });
  const start = new Date(`${key}T12:00:00`); const dates = Array.from({ length: 7 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return localDateKey(date); }); const previous = dates.map((date) => { const d = new Date(`${date}T12:00:00`); d.setDate(d.getDate() - 7); return localDateKey(d); });
  const totals = dayTotals(focusSessions); const currentMinutes = dates.reduce((sum, date) => sum + (totals[date] || 0), 0); const previousMinutes = previous.reduce((sum, date) => sum + (totals[date] || 0), 0); const sessions = focusSessions.filter((s) => dates.includes(s.date)); const completed = reminders.filter((r) => r.completed && dates.includes(r.date)).length; const planned = reminders.filter((r) => dates.includes(r.date)).length; const best = dates.sort((a,b) => (totals[b]||0)-(totals[a]||0))[0]; const quality = sessions.filter(s => s.quality).map(s => s.quality);
  const save = () => setWeeklyReflections((all) => ({ ...all, [key]: draft }));
  return <div className="space-y-7 animate-fadeIn"><div><p className="text-emerald-400 text-xs font-bold uppercase tracking-[.2em]">Reflect</p><h1 className="text-3xl font-bold text-white mt-1">Weekly review</h1><p className="text-sm text-neutral-400 mt-1">Week of {new Date(`${key}T12:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</p></div><div className="grid grid-cols-2 lg:grid-cols-3 gap-4"><Metric label="Total focus" value={formatFocusTime(currentMinutes)}/><Metric label="Sessions" value={sessions.length}/><Metric label="Tasks completed" value={`${completed} / ${planned}`}/><Metric label="Average session" value={formatFocusTime(sessions.length ? currentMinutes/sessions.length : 0)}/><Metric label="Current streak" value={`${streak.current} days`}/><Metric label="Best focus day" value={best && totals[best] ? new Date(`${best}T12:00:00`).toLocaleDateString(undefined,{weekday:'long'}) : '—'}/></div><section className="glass-panel rounded-3xl p-6 border border-neutral-800"><div className="flex items-center gap-2"><Activity className="w-5 h-5 text-emerald-400"/><h2 className="font-bold text-white">Week in context</h2></div><p className="text-sm text-neutral-300 mt-4">{previousMinutes ? `${formatFocusTime(currentMinutes)} this week, ${Math.abs(Math.round((currentMinutes - previousMinutes) / previousMinutes * 100))}% ${currentMinutes >= previousMinutes ? 'more' : 'less'} than last week.` : currentMinutes ? `${formatFocusTime(currentMinutes)} focused this week — keep building the rhythm.` : 'Complete a session to begin your weekly picture.'}</p>{quality.length >= 3 && <p className="text-sm text-neutral-400 mt-2">Average focus quality: <span className="text-white font-bold">{(quality.reduce((a,b)=>a+b,0)/quality.length).toFixed(1)} / 5</span></p>}</section><section className="glass-panel rounded-3xl p-6 border border-neutral-800 space-y-4"><div className="flex items-center gap-2"><CheckSquare className="w-5 h-5 text-emerald-400"/><h2 className="font-bold text-white">Reflection</h2></div><label className="block text-sm text-neutral-300">What went well?<textarea value={draft.wentWell} onChange={e => setDraft({...draft,wentWell:e.target.value})} className="glass-input mt-2 w-full p-3 rounded-xl text-sm h-24" placeholder="A small win is enough."/></label><label className="block text-sm text-neutral-300">What do you want to improve next week?<textarea value={draft.improve} onChange={e => setDraft({...draft,improve:e.target.value})} className="glass-input mt-2 w-full p-3 rounded-xl text-sm h-24" placeholder="Keep it specific and kind."/></label><button onClick={save} className="btn-emerald px-4 py-2 rounded-xl text-sm">Save reflection</button></section></div>;
};
const Metric = ({ label, value }) => <div className="glass-panel rounded-2xl p-4 border border-neutral-800"><p className="text-[11px] text-neutral-400 uppercase tracking-wider font-bold">{label}</p><p className="text-xl text-white font-bold mt-2">{value}</p></div>;
